### ISSUE TITLE
uninitialized constant BaconExpect::Matcher::SingleMethod on 10.13 and iOS 11...

### ISSUE THREAD

**Issue by digitalmoksha** [ijpiantanida/bacon-expect#1]
I use `bacon-expect` in a couple RubyMotion projects, and with the latest upgrades (macOS 10.13, iOS 11, RM 5.x) I'm getting the following error when running your tests:

```
  Simulate /Users/myuser/Downloads/_Safari/bacon-expect-master/spec_app/build/iPhoneSimulator-11.0-Development/sample_spec.app
2017-10-18 14:30:08.312 sample[88898:8848981] +[CATransaction synchronize] called within transaction
2017-10-18 14:30:08.670 sample[88898:8848981] *** Terminating app due to uncaught exception 'NameError', reason: '/Users/myuser/Downloads/_Safari/bacon-expect-master/lib/bacon-expect/matchers/eql.rb:2:in `<main>: uninitialized constant BaconExpect::Matcher::SingleMethod (NameError)
	from /Users/myuser/Downloads/_Safari/bacon-expect-master/lib/bacon-expect/matchers/eql.rb:4:in `<main>
	from /Users/myuser/Downloads/_Safari/bacon-expect-master/lib/bacon-expect/matchers/eql.rb:4:in `<main>
```

It's failing in my apps as well when I run specs.  Any ideas?

**Comment by eahanson** [comment]
I was having this problem too.

In a Slack message, Eamonn Webster suggested using their[ fork of bacon-expect](https://github.com/eamonn-webster/bacon-expect), which worked for me.

```
# gemfile
gem 'bacon-expect', github: 'eamonn-webster/bacon-expect'
```

**Comment by digitalmoksha** [comment]
Thanks for the pointer @eahanson !
